### ISSUE TITLE
Getting blackbox for evaluation from persisted genome

### ISSUE THREAD

**Issue by Matasx** [colgreen/sharpneat-refactor#35]
Hi,
I was able to create a custom experiment, train the network and persist the best genome. Now I want to put the trained genome to real world use, but I fail to see an easy way to do it. I had to change the visibility of `NeatUtils.CreateGenomeDecoder` to public and then use this code to get the black box:
```C#
using CustomTasks.MarketPredictor;
using SharpNeat.IO;
using SharpNeat.Neat;
using SharpNeat.Neat.Genome.IO;

var factory = new MarketPredictorFactory();
var config = JsonUtils.LoadUtf8("......\\src\\SharpNeat.Windows.App\\config\\experiments-config\\market-predictor.config.json");
var experiment = factory.CreateExperiment(config.RootElement);

var metaNeatGenome = NeatUtils.CreateMetaNeatGenome(experiment);

var loader = NeatGenomeLoaderFactory.CreateLoaderDouble(metaNeatGenome);
var genome = loader.Load("my.genome");

var decoder = NeatUtils.CreateGenomeDecoder(experiment);
var box = decoder.Decode(genome);
```

Is there easier or other recommended way to do this?
Thank you in advance.

**Comment by colgreen** [comment]
Thanks for the detailed example source code.

That is probably the best that can be done right now, apart from writing your own class to read the genome data directly into one of the NeuralNet implementations. This poor IO experience has been flagged up in a couple of other issues, so I will endeavour to improve this.  Right now though it sounds like you got it working at least, albeit with far more convoluted code than might be expected. and that does look like the correct series of steps given the various helper methods and classes available.

**Comment by colgreen** [comment]
This issue is now resolved. 

A new class called NetFileModel is an in-memory representation of a neural net and some associated metadata (i.e., input and output count, whether the network is cyclic or acyclic, the number of cycles per activation if it is acyclic, and the activation function).

Instances of NetFileModel can be saved and loaded to file, with a format basically the same as the existing genome format, with the addition of a 'cycles-per-activation' data item when the genomes/networks are cyclic.

Instances of NetFileModel  can be converted to and from a NeatGenome<double>.

Instances of NetFileModel can be converted to (but not from) a neural net implementation using these methods:

```
static IBlackBox<double> ToNeuralNet(
        NetFileModel model, ...

static IBlackBox<double> ToAcyclicNeuralNet(
        NetFileModel model, ...

static IBlackBox<double> ToAcyclicNeuralNet(
        NetFileModel model, ...
```

Using ```ToNeuralNet()``` should be sufficient, but you can call the more specific methods ```ToAcyclicNeuralNet``` or ```ToCyclicNeuralNet``` if you know what type of network you expect; those methods will throw an exception if the cyclicity of the loaded net file isn't as expected.

Once converted to an ```IBlackBox<double>``` the black-box / neural-net can be be assigned input values, activated, and the output values read, as normal.
